title:            INSTEAD
description:      Simple Text Adventure, The Interpreter
url:              http://instead.libcode.org
signoff:          Peter Kosyh
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Blog
    url:          /
  - name:         About
    url:          /about
  - name:         Screenshots
    url:          /screenshots
  - name:         Games
    url:          /games
  - name:         Forum
    url:          /talk
    external:     true
  - name:         Doc
    url:          /doc
  - name:         Code
    url:          http://github.com/instead-hub/instead
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart